= Java Arrays, Wat!

== Java Arrays: Surprising Behaviours

Arrays in Java can behave in unexpected ways. Let's explore a few quirks.

== Is it an Array or Not?

Consider the following declaration:

[source,java]
----
Serializable array = new Serializable[9];
----

Is `array` an array or a scalar? In fact, it’s a scalar reference that points to an array. Similarly:

[source,java]
----
Object o = new Object[9];
----

Here, you can assign an array to an `Object` variable because arrays are also objects in Java. Additionally, arrays are `Serializable`, so they can be assigned to a `Serializable` reference as well.

== Where Did My `[]` Go?

Java syntax can produce some surprising results due to backward compatibility. Consider this method signature:

[source,java]
----
public static int method(int[]... args)[] {
    return args[0];
}
----

In this example:

- `args` is of type `int[][]`.
- The return type is `int[]`, indicated by the `[]` after the method declaration.

This syntax isn’t part of the Java Language Specification (JLS); it’s allowed in OpenJDK for backward compatibility.

== What’s the Difference Between `int[] array` and `int array[]`?

There is a subtle difference when additional brackets follow:

[source,java]
----
int[] array, x[];
----

and

[source,java]
----
int array[], y[];
----

In these cases:

- `x` is of type `int[][]`.
- `y` is of type `int[]`.

== What Happens If an Array Initialisation Is Too Large?

Consider initialising a large array like this:

[source,java]
----
public static final int[] VALUES = {
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
    /* many, many lines deleted */
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,
};
----

This produces an error:

[quote]
----
Error:(6, 31) java: code too large
----

It may seem odd that the error is not about the array size but rather the code size. This is because arrays are initialised in bytecode, which generates code to create and populate the array one element at a time. When the array is large, the generated bytecode exceeds Java's method size limit (65,535 bytes).

Due to this limit, large initialised arrays or a high number of enum values may result in compilation errors.

== The Code

Code to run the examples that compile above is available here: https://github.com/Vanilla-Java/Blog/blob/main/java-misconceptions/src/main/java/blog/vanillajava/JavaArraySurprises.java[JavaArraySurprises.java].

== About the Author

As the CEO of https://chronicle.software/[Chronicle Software], https://www.linkedin.com/in/peterlawrey/[Peter Lawrey] leads the development of cutting-edge, low-latency solutions trusted by https://chronicle.software/8-out-of-11-investment-banks/[8 out of the top 11 global investment banks]. With decades of experience in the financial technology sector, he specialises in delivering ultra-efficient enabling technology that empowers businesses to handle massive volumes of data with unparalleled speed and reliability. Follow Peter on https://bsky.app/profile/peterlawrey.bsky.social[BlueSky] or https://mastodon.social/@PeterLawrey[Mastodon].
